/* eslint-disable */

// Generated by ChatGPT to test StandardJS abilities for catching and fixing errors
// This file is the only file that is checked by the workflow.

function isEven (num) {
  return num % 2 === 0
}

const numbers = [1, 2, 3, 4, 5]
const evenNumbers = numbers.filter(isEven)

console.log('Even numbers:', evenNumbers)

for (let i = 0; i < numbers.length; i++) {
  console.log(`Number ${numbers[i]} is ${isEven(numbers[i]) ? 'even' : 'odd'}`)
}
